### PR TITLE
Upgrade to go 1.21

### PR DESCRIPTION
**Pull request by mwasilew2**
Upgrades from 1.19 to 1.21

### CODE REVIEW

**Comment by mwasilew2** [comment]
`staticcheck` doesn't support `1.21`: https://staticcheck.io/changes/2023.1/

**Comment by tomasmik** [comment]
> `staticcheck` doesn't support `1.21`: https://staticcheck.io/changes/2023.1/ , that's why the lint job is failing

This is quite ugly. Are there any news on when it would be supported? I kinda like the linting.

**Comment by michieldewilde** [comment]
@michalg9 
```
- name: Mark source directory as safe.
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
```
adding this as a step after you checkout the code should solve this problem.

**Comment by mwasilew2** [comment]
@michieldewilde good catch!

**Review by michieldewilde — APPROVED** [review]

**Review by tomasmik — APPROVED** [review]

**Pull request merged**
