### PR TITLE
chore: added install method with aqua

### PR DESCRIPTION
**Pull request by ponkio-o**
Hi, I added install method with [aqua](https://aquaproj.github.io/) in README.

related PR: https://github.com/aquaproj/aqua-registry/pull/16197

### CODE REVIEW

**Review by mbialon — DISMISSED** [review]
LGTM

**Review by tomasmik — CHANGES_REQUESTED** [review]
Thank you for contributing but actually I'm unsure about this. Never heard of aqua, need to check what it is.

**Comment by tomasmik** [comment]
Sorry but unfortunately we've decided to decline this change. We feel that this package (version) manager is a bit too little known to be included in the readme in this way. However we've noted that `spacectl` can be installed using `aqua` and will include it when we update the readme to accommodate additional install instructions without obscuring others.

Thank you again for your contribution.

**Comment by booniepepper** [comment]
What is the criteria for "known enough"? Aqua is a fantastic project, and it's been growing in popularity with Japanese companies. I expect it to continue growing in popularity over time and hit some kind of inflection point. There are a few listed here https://github.com/aquaproj/aqua#who-uses-aqua and also Mercari is using it now too

**Pull request closed without merging**
