### PR TITLE
feat(spacectl/worker): allow draining/undraining of workers

### LINKED ISSUE #68: Request: drain and undrain workers
It would be nice to drain and undrain workers using the spacectl

### PR DESCRIPTION
**Pull request by jpJuni0r**
Closes #68.

### CODE REVIEW

**Comment by peterdeme** [comment]
Will review and test tomorrow.

**Comment by peterdeme** [comment]
@jpJuni0r I tested it locally, looks good to me. Just one minor thing, can you add some log output to both commands? something like `fmt.Printf("Successfully drained worker %s\n", workerid)`

**Review by peterdeme — CHANGES_REQUESTED** [review]
Just the above comment

**Comment by jpJuni0r** [comment]
No problem. 😊

**Pull request merged**
